{
  "title": "The Mole Who Got Charged",
  "subtitle": "When doing the right thing costs you everything.",
  "author": "Manus AI",
  "date": "February 4, 2026",
  "content": [
    "The decision wasn't made in a boardroom. It was made at a kitchen table.",
    "That's where most of the hard choices happen in this industry. Not the ones about stock prices or quarterly earnings, but the ones about survival. About integrity. About whether you can look your kids in the eye and tell them you did the right thing, even when the right thing feels like walking off a cliff.",
    "For the team at Freedom Cannabis, the choice was simple, even if the consequences were terrifying. The regulator—the Alberta Gaming, Liquor and Cannabis Commission (AGLC)—had asked for help. They needed someone on the inside. Someone to blow the whistle on the 'pay-to-play' schemes that were rotting the sector from the inside out.",
    "So they said yes.",
    "They didn't say yes because it was profitable. In fact, they knew it would cost them. They burned bridges with major retailers. They walked away from lucrative deals. They loaded $1.2 million in inventory based on a 'wink-wink' promise that they'd be safe if they played ball.",
    "They were the good guys. The cooperators. The ones trying to clean up the mess.",
    "———",
    "The betrayal didn't happen all at once. It happened in slow motion.",
    "First, it was the silence. The phone calls that weren't returned. The meetings that got pushed back. Then, it was the letter.",
    "Not a thank-you note. Not a commendation. A charge.",
    "The very evidence they had voluntarily provided—the emails, the dates, the names—was now being used against them. The Investigation Division, operating in a silo so deep it might as well have been on another planet, had decided that the whistleblower was the criminal.",
    "And the gangsters? The ones demanding the payoffs? The ones Freedom had risked everything to expose?",
    "They walked free.",
    "———",
    "It feels like a bad movie script. The kind where the hero gets framed and the villain drives off into the sunset. But for the 50 people working at Freedom Cannabis, this isn't a movie. It's their livelihood.",
    "These are real jobs. Real families. Real mortgages paid by the work done in that facility. And now, because of a bureaucratic glitch—a failure of the left hand to know what the right hand is doing—all of that is at risk.",
    "A $100,000 fine isn't just a number on a balance sheet. For a company that has already taken a massive financial hit to do the right thing, it's a potential death sentence.",
    "———",
    "Today, they walk into a hearing room. They don't have a team of high-priced lawyers. They don't have a polished PR strategy. They have the truth.",
    "They have a timeline that shows exactly what happened. They have the emails. They have the promises.",
    "But mostly, they have a question.",
    "Is this what we want? Do we want a system where the people who try to help are the ones who get hurt? Do we want a regulator that punishes its allies and ignores its enemies?",
    "Or do we want someone to be the adult in the room?",
    "———",
    "The 'Ruby Red' client—the single mom trying to make ends meet, the one this team fights for every day—knows what fairness looks like. She knows that you don't punish the person who tells the truth.",
    "She knows that when you lose sight of the objective, you make enemies of your friends.",
    "Freedom Cannabis was the mole. They did their job. Now, it's time for the AGLC to do theirs.",
    "Dismiss the charge. Close the file. Let the good guys get back to work."
  ]
}
