CREATE TABLE `story_submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`submitterName` varchar(255) NOT NULL,
	`submitterEmail` varchar(320),
	`submitterTitle` varchar(255),
	`submitterOrganization` varchar(255),
	`userId` int,
	`q1ToughestConversation` text,
	`q2BuildingTrust` text,
	`q3FirstInteraction` text,
	`q4DenialConversation` text,
	`q5CommunityResources` text,
	`q6ClientWins` text,
	`q7SecretWeapon` text,
	`q8IdealBotFeatures` text,
	`q9AdditionalThoughts` text,
	`q10MemorableStory` text,
	`status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`reviewNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `story_submissions_id` PRIMARY KEY(`id`)
);
